### ISSUE TITLE
CLI fails to start on windows with signal import issue

### ISSUE THREAD

**Issue by jackgerrits** [jupyter-server/kernel_gateway#398]
## Description

There is a crash immediately on startup on Windows.

## Reproduce

```
jupyter kernelgateway
```

Powershell
```
jupyter kernelgateway
```

Output:
```
Traceback (most recent call last):
 File "c:\users\me\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_
main
   return _run_code(code, main_globals, None,
 File "c:\users\me\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
   exec(code, run_globals)
 File "C:\Users\me\AppData\Local\Programs\Python\Python38\Scripts\jupyter-kernelgateway.EXE\__main__.
py", line 7, in <module>
   sys.exit(launch_instance())
 File "c:\users\me\appdata\local\programs\python\python38\lib\site-packages\jupyter_core\application.
py", line 283, in launch_instance
   super().launch_instance(argv=argv, **kwargs)
 File "c:\users\me\appdata\local\programs\python\python38\lib\site-packages\traitlets\config\applicat
ion.py", line 1074, in launch_instance
   app.initialize(argv)
 File "c:\users\me\appdata\local\programs\python\python38\lib\site-packages\kernel_gateway\gatewayapp
.py", line 536, in initialize
   self.init_signal()
 File "c:\users\me\appdata\local\programs\python\python38\lib\site-packages\kernel_gateway\gatewayapp
.py", line 724, in init_signal
   signal.signal(signal.SIGQUIT, self._signal_stop)
AttributeError: module 'signal' has no attribute 'SIGQUIT'
```

## Expected behavior

Does not crash

## Context

- Operating System and version: Windows 11
- Browser and version: N/A
- Jupyter Server version: jupyter-kernel-gateway==3.0.0,  jupyter-server==2.12.5 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by RohanGd** [comment]
This bug still exists.
```
from autogen.coding import CodeBlock
from autogen.coding.jupyter import JupyterCodeExecutor, LocalJupyterServer

with LocalJupyterServer() as server:
    executor = JupyterCodeExecutor(server)
    print(
        executor.execute_code_blocks(
            code_blocks=[
                CodeBlock(language="python", code="print('Hello, World!')"),
            ]
        )
    )
```

Produced Error: 

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[2], line 4
      1 from autogen.coding import CodeBlock
      2 from autogen.coding.jupyter import JupyterCodeExecutor, LocalJupyterServer
----> 4 with LocalJupyterServer() as server:
      5     executor = JupyterCodeExecutor(server)
      6     print(
      7         executor.execute_code_blocks(
      8             code_blocks=[
   (...)     11         )
     12     )

File c:\RPTU Sem 1\GenAI\portfolio_exam\venv\Lib\site-packages\autogen\coding\jupyter\local_jupyter_server.py:59, in LocalJupyterServer.__init__(self, ip, port, token, log_file, log_level, log_max_bytes, log_backup_count)
     57 # Remove as soon as https://github.com/jupyter-server/kernel_gateway/issues/398 is fixed
     58 if sys.platform == "win32":
---> 59     raise ValueError("LocalJupyterServer is not supported on Windows due to kernelgateway bug.")
     61 # Check Jupyter gateway server is installed
     62 try:

ValueError: LocalJupyterServer is not supported on Windows due to kernelgateway bug.
```
